# Pre-build script (FirmwareSpec.md §15.3, §20.3): the settings page from
# data/portal/ (index.html with style.css and app.js inlined) is lightly
# minified, gzipped and written to src/net/page_gz.h as a byte array, only
# when it changed (so an unchanged page does not rebuild api.cpp).
import gzip, os, re, hashlib

Import("env")

ROOT = env.subst("$PROJECT_DIR")
SRC = os.path.join(ROOT, "data", "portal")
OUT = os.path.join(ROOT, "src", "net", "page_gz.h")


def minify_css(s):
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    s = "\n".join(line.strip() for line in s.splitlines() if line.strip())
    return s


def minify_js(s):
    # Block comments and whole-line // comments only: anything inside a string
    # or a regex literal is left alone.
    s = re.sub(r"^\s*/\*.*?\*/\s*$", "", s, flags=re.S | re.M)
    out = []
    for line in s.splitlines():
        t = line.strip()
        if not t or t.startswith("//"):
            continue
        out.append(t)
    return "\n".join(out)


def build():
    html = open(os.path.join(SRC, "index.html"), encoding="utf-8").read()
    css = minify_css(open(os.path.join(SRC, "style.css"), encoding="utf-8").read())
    js = minify_js(open(os.path.join(SRC, "app.js"), encoding="utf-8").read())
    html = html.replace('<link rel="stylesheet" href="style.css">', "<style>" + css + "</style>")
    html = html.replace('<script src="app.js"></script>', "<script>" + js + "</script>")
    html = "\n".join(line.strip() for line in html.splitlines() if line.strip())
    raw = html.encode("utf-8")
    gz = gzip.compress(raw, compresslevel=9, mtime=0)
    digest = hashlib.sha1(gz).hexdigest()[:12]
    header = "// Generated by tools/build_page.py from data/portal/ -- do not edit.\n"
    header += "// page %d bytes, gzip %d bytes, sha1 %s\n#pragma once\n#include <stdint.h>\n" % (len(raw), len(gz), digest)
    header += "static const uint32_t PAGE_GZ_LEN = %d;\nstatic const uint8_t PAGE_GZ[] PROGMEM = {\n" % len(gz)
    rows = []
    for i in range(0, len(gz), 24):
        rows.append("  " + ",".join("0x%02x" % b for b in gz[i:i + 24]) + ",")
    header += "\n".join(rows) + "\n};\n"
    old = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
    if old != header:
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        open(OUT, "w", encoding="utf-8").write(header)
    print("portal page: %d bytes, %d gzipped (%s)" % (len(raw), len(gz), "written" if old != header else "unchanged"))


build()
